# Generated by Django 3.2.7 on 2021-09-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.IntegerField()),
                ('Stu_name', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecturer_name', models.CharField(max_length=30)),
                ('Lecturer_subject', models.CharField(max_length=30)),
                ('dept_name', models.ManyToManyField(to='InfoApp.Department')),
            ],
        ),
    ]
